### ISSUE TITLE
Could you replace wpe-webgl dependency?

### ISSUE THREAD

**Issue by Mapaler** [kiootic/pad-resources#1]
I've been trying for months and I've been unable to run this project successfully.

This program also compiles under Windows using Linux commands, so there are always errors.
![Screenshot 2019-07-09 17 52 48](https://user-images.githubusercontent.com/6565860/60880384-2ad5b500-a276-11e9-8e5f-b590d3b10ed3.png)

But even under Linux, I haven't run the animation successfully.
![Screenshot 2019-07-09 17 57 28](https://user-images.githubusercontent.com/6565860/60880521-5f497100-a276-11e9-8e09-a29b6eb90005.png)
![Screenshot 2019-07-09 18 38 17](https://user-images.githubusercontent.com/6565860/60881683-c700bb80-a278-11e9-82fc-b62fa8fd807f.png)

**Comment by kiootic** [comment]
I've updated it in [v2 branch](https://github.com/kiootic/pad-resources/tree/v2) to output Spine data instead, so you can render them using other programs.
