### ISSUE TITLE
issues extracting for certain cards

### ISSUE THREAD

**Issue by izenn** [kiootic/pad-resources#2]
I'm having trouble extracting data from the following cards:
5546
5548
5557
5740
5973
6156

Here is the error i'm getting:
```
$ yarn render --bin data/USA/bin/mons_6156.bin --out test.png
yarn run v1.22.5
$ ts-node . render --bin data/USA/bin/mons_6156.bin --out test.png

unexpected error:  TypeError: Cannot read property 'createBuffer' of null
    at new GLContext (/home/izenn/pad/pad-resources/src/renderer/gl-context.ts:43:28)
    at new Renderer (/home/izenn/pad/pad-resources/src/renderer/renderer.ts:25:20)
    at new AnimatedRenderer (/home/izenn/pad/pad-resources/src/renderer/animated.ts:68:5)
    at /home/izenn/pad/pad-resources/src/actions/render.ts:49:16
    at Generator.next (<anonymous>)
    at /home/izenn/pad/pad-resources/src/actions/render.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/izenn/pad/pad-resources/src/actions/render.ts:3:12)
    at main (/home/izenn/pad/pad-resources/src/actions/render.ts:29:12)
    at /home/izenn/pad/pad-resources/src/index.ts:19:41
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

any help is appreciated. I'm more than willing to donate if that would help

**Comment by kiootic** [comment]
I've updated it in [v2 branch](https://github.com/kiootic/pad-resources/tree/v2) to output Spine data instead, so you can render them using other programs.

**Comment by izenn** [comment]
Thanks so much!  would you also be able to provide an example on how to render using other programs? and should i be using yarn extract? (sorry for the noobish questions)

thanks!

**Comment by kiootic** [comment]
`yarn extract `should output Spine data files now, so you can render it using any Spine compatible renderer. I've added a sample renderer to the repo. Just start an HTTP server and goes to `http://localhost:8000/renderer/` and you can see it rendered.

**Comment by izenn** [comment]
not sure what happened.  I just re-cloned the repo and now i get the following error:
```
% yarn extract --out test/ data/USA/bin/mons_6156.bin
yarn run v1.22.10
warning ../../../package.json: No license field
$ ts-node . extract --out test/ data/USA/bin/mons_6156.bin

unexpected error:  src/actions/extract.ts:9:10 - error TS2724: '"../models/spine"' has no exported member named 'loadISA'. Did you mean 'loadISC'?

9 import { loadISA, loadISC } from '../models/spine';
           ~~~~~~~

  src/models/spine.ts:10:17
    10 export function loadISC(isc: ISC, skeleton: SpineSkeleton, atlas: SpineAtlas) {
                       ~~~~~~~
    'loadISC' is declared here.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kiootic** [comment]
Sorry, a typo there. Please get the latest commit and try again.

**Comment by izenn** [comment]
normally with node there is a .js to run for the web server, what should i use for this project? (i'm not familiar with typescript)

**Comment by kiootic** [comment]
Just serve the repo as static server. I used `python3 -m http.server` for this, or you can use any other static servers.

**Comment by izenn** [comment]
that worked perfectly!  1 last question: is it possible to (from the command line) grab a screen shot? (similar to the png export from v1?)

thanks again!!

**Comment by kiootic** [comment]
Rendering the images need to use OpenGL-rendering. Previously many reported it's hard to use across platform, so I omitted it at the moment. I'll open an issue to track this, and you  may try using headless chrome in the meanwhile.
